spring:
  datasource:
    url: ${MUSIC_MANIA_AWS_RDS_DB_URL}
    username: ${MUSIC_MANIA_AWS_RDS_DB_USERNAME}
    password: ${MUSIC_MANIA_AWS_RDS_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  error:
    include-message: always

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
